config/routes.rb
Rails.application.routes.draw do
  root to: "public#root"
  get "show/:id" => "public#show"
  namespace :private do
    resources :articles
    post "articles/new_file" => "articles#new_file"
    get "delete_file" => "articles#delete_file"
    get "window/:user_id/:article_id/:file" => "articles#window"
  end
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/private.rb
module Private
  def self.table_name_prefix
    'private_'
  end
end

app/models/private/article.rb
class Private::Article < ApplicationRecord
  belongs_to :user
  mount_uploader :path, FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/private/articles_controller.rb
class Private::ArticlesController < ApplicationController
  layout 'articles'
  before_action :authenticate_user!
  before_action :set_private_article, only: [:show, :edit, :update, :destroy]

  # GET /private/articles
  # GET /private/articles.json
  def index
    @private_articles = Private::Article.where(user_id: current_user.id)
  end

  # GET /private/articles/1
  # GET /private/articles/1.json
  def show
    @path = "#{Dir.pwd}/public#{@private_article.path}"
    begin
      @file = File.open(@path)
    rescue
      redirect_to action: 'index'
    end
  end

  # GET /private/articles/new
  def new
    @private_article = Private::Article.new
  end

  # GET /private/articles/1/edit
  def edit
    begin
      @base_dir = File.dirname("#{@private_article.path}")
      @dir = Dir.open("./public/#{@base_dir}")
      @path = "#{Dir.pwd}/public#{@private_article.path}"
      begin
        @file = File.open(@path, "r+")
      rescue
        @private_article.destroy
        redirect_to action: 'index'
      end
    rescue
      redirect_to action: 'index'
    end
    #@s = File::Stat.new(@path)
  end

  # POST /private/articles
  # POST /private/articles.json
  def create
    @private_article = Private::Article.new(private_article_params)

    respond_to do |format|
      if @private_article.save
        format.html { redirect_to action: 'index', notice: 'Article was successfully created.' }
        format.json { render :index, status: :created, location: @private_article }
      else
        format.html { render :new }
        format.json { render json: @private_article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def new_file
    @path = params[:path]
    @dir = File.dirname(@path)
    @count = Dir::entries(@dir).count
    @new_file = "#{@dir}/#{@count}.txt"
    File.rename("#{@path}", "#{@new_file}")
    File.open(@path, "w") {
      |file| file.write "#{params[:text]}"
    }
    redirect_to action: 'index'
  end
  
  def delete_file
    @path = "public#{params[:file_name]}"
    File.delete(@path)
    redirect_to action: 'index'
  end
  
  def window
    @file = File.open("./public/uploads/#{params[:user_id]}/#{params[:article_id]}/#{params[:file]}.txt", "r")
    render plain: @file.read
  end
  
  # PATCH/PUT /private/articles/1
  # PATCH/PUT /private/articles/1.json
  def update
     
    respond_to do |format|
      if @private_article.update(private_article_params)
        format.html { redirect_to @private_article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @private_article }
      else
        format.html { render :edit }
        format.json { render json: @private_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private/articles/1
  # DELETE /private/articles/1.json
  def destroy
    begin
      @base_dir = File.dirname("public#{@private_article.path}")
      @dir = Dir.open(@base_dir)
      @dir.each do |file|
        if /txt/ =~ file
          File.delete("#{@base_dir}/#{file}")
        end
      end
      Dir.rmdir(@base_dir)
    rescue
    #DO NOTHING
    end
    @private_article.destroy
    respond_to do |format|
      format.html { redirect_to private_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_article
      @private_article = Private::Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def private_article_params
      params.require(:private_article).permit(:user_id, :name, :path, :source)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def root
        @private_articles = Private::Article.all
    end
    
    def show
        @private_article = Private::Article.find(params[:id])
        @file = File.open("./public#{@private_article.path}", "r")
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  def after_sign_in_path_for(resource)
     private_articles_url
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def after_sign_in_path_for(resource)
     private_articles_url
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/private/articles_helper.rb
module Private::ArticlesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Translator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>翻訳文置き場|目指せ翻訳家</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'scaffolds', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
      <div class="row">
        <span class="col-sm-4 logout">
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-primary" %>
        </span>
        <span class="col-sm-8"><%= link_to '新規登録', new_private_article_path, class: "btn btn-dark" %></span>
      </div>
      <main>
          <%= yield %>
      </main>
      <script>
        $(".submit").mouseenter(function(){
          $(this).addClass("submit-color");
        });
        $(".submit").mouseleave(function(){
          $(this).removeClass("submit-color");
        });
        $(".back").click(function(){
       history.back(); 
    });
    
    $(".back").mouseenter(function(){
        $(this).addClass("back-color");
    });
    $(".back").mouseleave(function(){
        $(this).removeClass("back-color");
    });
      </script>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>翻訳文置き場|目指せ翻訳家</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'public', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
      <main>
          <%= yield %>
      </main>
      <script>
        
      </script>
  </body>
</html>

app/views/private/articles/_form.html.erb
<%= form_with(model: private_article, local: true) do |form| %>
  <% if private_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private_article.errors.count, "error") %> prohibited this private_article from being saved:</h2>

      <ul>
      <% private_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :user_id %>
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
  </div>

  <div class="field">
    <p class="label">訳文タイトル: <%= form.text_field :name %></p>
  </div>

  <div class="field">
    <p class="label">ファイルアップロード: <%= form.file_field :path %></p>
  </div>
  
  <div class="field">
    <p class="label">ソースＵＲＬ: <%= form.text_field :source %></p>
  </div>
  
  <div class="action">
    <%= button_tag :type => "submit", :class =>"btn submit" do %>
      <i class="fas fa-plus"></i> 新規訳文登録
    <% end %>
  </div>
  
<% end %>

app/views/private/articles/edit.html.erb
<%= form_with(model: @private_article, local: true) do |form| %>
  <% if @private_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private_article.errors.count, "error") %> prohibited this private_article from being saved:</h2>

      <ul>
      <% private_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <span class="inline_block back">
    <i class="fas fa-hand-point-left"></i> <%= link_to 'Back', private_articles_path %>
  </span>
  <div class="field">
    <%= form.hidden_field :user_id, value: "#{current_user.id}" %>
  </div>

  <div class="field">
    <p class="label">タイトル：<%= form.text_field :name, value: "#{@private_article.name}" %></p>
  </div>
  
  <div class="field">
    <p class="label">ソースＵＲＬ：<%= form.text_field :source, value: "#{@private_article.source}" %></p>
  </div>
  
  <div class="field">
    <%= form.hidden_field :path, value: "#{@file}" %>
  </div>
  
  <div class="actions">
    <%= button_tag :type => "submit", :class =>"btn submit" do %>
      <i class="far fa-edit"></i> リソース更新
    <% end %>
  </div>
<% end %>

<%= button_tag :class=> "btn open-drop submit" do %>
  <i class="fas fa-scroll"></i> 訳文推敲
<% end %>


<div class="dropdown">
  <span class="inline_block back">
    <i class="fas fa-hand-point-left"></i> <%= link_to 'Back', private_articles_path %>
  </span>
<div class="nav inline_block">
  <% @dir.each do |file| %>
    <% unless "#{@base_dir}/#{file}" == "#{@private_article.path}" %>
      <% if /txt/ =~ file %>
        <abbr title="クリックで旧ファイルを表示">
          <%= link_to "#{file}", private_url(article_id: @private_article.id, user_id: current_user.id, file: file), target: "_blank" %>
        </abbr>
        <abbr title="旧ファイルを削除">
          <%= link_to "削除 ", private_delete_file_url(file_name: "#{@base_dir}/#{file}"), data: { confirm: 'Are you sure?' } %>
        </abbr>|
      <% end %>
    <% end %>
  <% end %>
  <% @dir.close %>
</div>

<%= form_tag({ controller: :articles, action: :new_file }) do %>
  <%= button_tag :type => "submit", :class =>"btn submit" do %>
    <i class="far fa-edit"></i> ファイル更新
  <% end %>
  <br>
  <div class="field">
    <%#= text_field_tag :text, "#{@file.read}", class:"edit-text" %>
    <% begin %>
      <%= text_area_tag :text, "#{@file.read}", class:"edit-text" %>
    <% end %>
    <%= hidden_field_tag :path, "#{@path}" %>
  </div>
  <%#= submit_tag("update") %>
<% end %>
</div>

<script>
  $(".open-drop").click(function(){
    $(".dropdown").toggle();
  });
</script>

app/views/private/articles/index.html.erb
<p id="notice"><%= notice %></p>

  <% @private_articles.each do |private_article| %>
  <div class="index-list">
    <div class="row">
      <p class="col-sm-4 index-title"><%= private_article.name %></p>
      <div class="col-sm-8">
      <%= link_to '閲覧', private_article, class: "btn btn-info" %>
      <%= link_to '推敲', edit_private_article_path(private_article), class: "btn btn-success" %>
      <%= link_to '削除', private_article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
    <% begin %>
      <% @file = File.open("./public/#{private_article.path}", "r") %>
        <div class="index-text"><%= @file.read %></div>
        <%= @file.close %>
    <% rescue %>
        <%# DO NOGHIN %>
    <% end %>
  </div>
  <% end %>
  
<br>
<script>
  $('.index-list').mouseenter(function(){
    $(this).addClass("index-list-color");
  });
  $('.index-list').mouseleave(function(){
    $(this).removeClass("index-list-color");
  });
</script>

app/views/private/articles/new.html.erb
<span class="inline_block back">
    <i class="fas fa-hand-point-left"></i> <%= link_to 'Back', private_articles_path %>
 </span>
<%= render 'form', private_article: @private_article %>

app/views/private/articles/show.html.erb
<p id="notice"><%= notice %></p>
<span class="inline_block back">
    <i class="fas fa-hand-point-left"></i> <%= link_to 'Back', private_articles_path %>
 </span>
<div class="show-text">
    <% begin %>
        <%= @file.read %>
    <% end %>
</div>

app/views/private/articles/window.html.erb
<%#= @file.read %>
<%# @file.close %>